# Common label to be applied
commonLabels:
  variant: stage

namespace: roar-stage

# List of resource files that kustomize reads, modifies
# and emits as a YAML string
resources:
- ./db
- ./web
- namespace.yaml
- mysql-db-configmap.yaml






          
